# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b04eb641b048557e1a056b703076ac792aebd95f27ad78cf1ff112a001836c7bc9b91ab5212bd867e9310bef22c74252a03382e63d453a119baf382ae4e017d

test:
  secret_key_base: 1005a6c6d8d76aa45149143c59db4ece511a6a25e1a620d8b928b1083dc596c0c6b48c734be52f5697b49958593ac7f6af60d6d84c80eb74dcb7d9e829470914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
